server:
  port: 8006
  servlet:
    context-path: /${spring.name}/${spring.version}
spring:
  name: album
  version: v1
  datasource:
    #type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://127.0.0.1:3306/album?useUnicode=true&characterEncoding=utf-8&allowMutiQueries=true&serverTimezone=GMT%2B8&useSSL=false
    url: jdbc:mysql://localhost:3306/album?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: oyyp1234@
logging.level.root: info
logging.config: classpath:logback-spring.xml
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.oy.album.dao
